### ISSUE TITLE
[FR] xxHash

### ISSUE THREAD

**Issue by thareh** [bmx-ng/crypto.mod#3]
Good day,

A nice addition at some point would be **xxHash** "Extremely fast hash algorithm".

https://github.com/Cyan4973/xxHash

Cheers!

**Comment by woollybah** [comment]
Interestingly, we already use xxhash (`blitz.mod/hash/....`) for our string hashing.

We could, of course, expose it for use generally.

**Comment by thareh** [comment]
Ah yes, that's right - I remember seeing it now!

That'd be very nice indeed.

Cheers!

**Comment by thareh** [comment]
Thank you very much!
